on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2-beta
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
      with:
         path: './src/github.com/kevinburke/twilio-go'
    # staticcheck needs this for GOPATH
    - run: echo "::set-env name=GOPATH::$GITHUB_WORKSPACE"
    - run: echo "::set-env name=PATH::$GITHUB_WORKSPACE/bin:$PATH"
    - name: Download dependencies
      run: go get -t -v ./...
      working-directory: './src/github.com/kevinburke/twilio-go'
    - name: Run tests
      run: make lint race-test-short
      working-directory: './src/github.com/kevinburke/twilio-go'
